config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :questions

  resources :surveys do
    resources :questions
      resources :given_answers
    end

  root to: "surveys#index"

end

app/models/given_answer.rb
class GivenAnswer < ActiveRecord::Base
	belongs_to :question
	belongs_to :survey
	belongs_to :user

	#accepts_nested_attributes_for :survey
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :survey
	has_many :given_answers
	belongs_to :user

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |p|
				csv << p.attributes.values_at(*column_names)
			end
		end
	end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
	belongs_to :user
	has_many :questions, :dependent => :destroy
	has_many :given_answers , :dependent => :destroy

	accepts_nested_attributes_for :given_answers

	validates_presence_of :name 


	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :questions
         has_many :given_answers
         has_many :surveys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user! , except: [:show , :index ]
end

app/controllers/given_answers_controller.rb
class GivenAnswersController < ApplicationController
  before_action :set_given_answer, only: [:show, :edit, :update, :destroy]

  #before_filter :find_survey!
  respond_to :html

  def index
    @given_answers = GivenAnswer.all
    respond_with(@given_answers)
  end

  def show
    respond_with(@given_answer)
  end

  def new
   # raise params.inspect
    @given_answer = GivenAnswer.new(given_answer_params)
  end

  def edit
  end


    def create
      #raise params.inspect
      #@given_answer=GivenAnswer.new(:survey_id => params[:survey_id], :question_id => params[:question_id] , :answer => params[:answer], :user_id => current_user.id)
          #if @given_answer.save
            params[:given_answer].each do |question_id, given_answer_attributes|
              answer=given_answer_attributes[:answer_option]
                #raise answer.inspect
              answer == if answer.is_a?(Array)
                  #raise answer.inspect
                stripped_answers = strip_checkbox_answers(answer)
                answer=stripped_answers.join('\n')    
              else
                 answer
              end
                #raise params.inspect
                  @attempts = GivenAnswer.new(:survey_id => params[:survey_id], :question_id =>question_id , :answer =>  answer, :user_id => current_user.id)
                  @attempts.save
            end
        @survey = Survey.find(params[:survey_id])
        redirect_to survey_given_answers_path(@survey) 
    end

    def strip_checkbox_answers(answer)
        answer.reject(&:blank?).reject { |t| t == "0" }
    end


    def show   
    end    


    def update
      @given_answer.update(given_answer_params)
      respond_with(@given_answer)
    end

    def destroy
      @given_answer.destroy
      respond_with(@given_answer)
    end

  private

    def find_survey!
      @question_group = Survey.find(params[:survey_id])
    end


    def given_answer_params
      answer_params = { params: (params[:given_answer] || {}) }
      #answer_params.merge(survey: @survey)
    end

    def set_given_answer
      @given_answer = GivenAnswer.find(params[:id])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @questions = Question.order(:question_text)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Prawn::Document.new
        send_data pdf.render, filename: 'report.pdf', type: 'application/pdf'
      end
      format.xls 
    end
    #@questions=@survey.questions
    #@given_answer=@questions.given_answers
    #respond_with(@questions)
  end

  def show
    @question=Question.find(params[:id])

    respond_with(@question)
  end

  def new
    @question = Question.new
    respond_with(@question)
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.save
    respond_with(@question)
  end

  def update
    # @totalResponseCount = 0
    # @averageResponseCount = 0

    # for @question.each do  |question|
    #   totalResponseCount += question.responseCount
    #   raise totalResponseCount.inpect
    #   averageResponseCount = totalResponseCount/Question.count
    # end
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    @question.destroy
    respond_with(@question)
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:survey_id, :type, :question_text, :position, :answer_options)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: :index

  respond_to :html

  def index
    @surveys = Survey.all
    respond_with(@surveys)
  end

  def show
    check = GivenAnswer.find_by(:user_id => current_user.id , :survey_id => @survey.id)
    if check.nil?
      @survey = Survey.find(params[:id])
      @given_answer = GivenAnswer.new  
      @questions = @survey.questions
    else
      flash[:error]="You already attempt this Survey....!!!"
      redirect_to surveys_path
    end
  end

  def new 
    @survey = Survey.new
    @survey.given_answers.build
    respond_with(@survey)
  end

  def edit
    @survey= Survey.find(params[:id])
    @question_results =GivenAnswer.where(:survey_id => @survey.id)
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.save
    respond_with(@survey)
  end

  def update
    @survey.update(survey_params)
    respond_with(@survey)
  end

  def destroy
    @survey.destroy
    respond_with(@survey)
  end

  private
    def set_survey
      @survey = Survey.find(params[:id])
    end

    def survey_params
      params.require(:survey).permit(:name, given_answers_attributes: [:id , :survey_id , :question_id , :user_id])
      # this is survey params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def render_answer_form_helper(question, form, index)
     	partial = question.types.to_s.downcase
     	render partial: "answer/#{partial}", locals: { f: form, answer: question , index: index }
   	end

   	def checkbox_checked?(answer, option)
      answers_delimiter = '0'
      answers = answer.answer_option.to_s.split(answers_delimiter)
      answers.include?(option)
    end
end

app/helpers/given_answers_helper.rb
module GivenAnswersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/given_answers/_form.html.erb
<%= form_for(@given_answer) do |f| %>
  <% if @given_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@given_answer.errors.count, "error") %> prohibited this given_answer from being saved:</h2>

      <ul>
      <% @given_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :survey_id %><br>
    <%= f.number_field :survey_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/given_answers/create.html.erb
<h4>Questions Attempted</h4>
<strong>Questions</strong> 

app/views/given_answers/edit.html.erb
<h1>Editing given_answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @given_answer %> |
<%= link_to 'Back', given_answers_path %>

app/views/given_answers/index.html.erb
 <h3>Report</h3>
<% @user = GivenAnswer.where(:user_id => current_user.id) %>
<table id="example" class="table table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Attempts</th>
      <th>Total Attempts</th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |given_answer| %>
      <tr>
        <td>
          <%= given_answer.question.question_text %>
        </td>
        <td><%#= given_answer.answer %>

            <% @options=GivenAnswer.where(:question_id => given_answer.question.id)%>
            <%#= raise @options.inspect %>
            <% @options.map(&:answer).uniq.each do |option| %>
                 <% if given_answer.question.types == "checkbox" %>
                      <% checkbox_array=option.split('\n') %>
                          <% checkbox_array.each do |checkbox_ans| %>
                              <% if checkbox_ans.empty? %>
                               <% else %>
                                  <%= checkbox_ans %><br>
                                <% end %>
                          <% end %>
                  <% else %>
                      <%= option %><br> 
                  <% end %>
              <% end %>
        </td>
        <td>
          <%= @options.count %>
        </td>
        <td>
          <% checkbox_array=[] %> 
          <%  @options.map(&:answer).uniq.each do |option| %>
            <% if given_answer.question.types == "checkbox" %>
              <% checkbox_array=checkbox_array + option.split('\n') %>          
            <% else %>      
              <% @counts = GivenAnswer.where(:answer => option) %>  
              <%= @counts.count %><br>    
            <% end%>
          <% end%>
          <% checkbox_array.uniq.each do |checkbox_ans| %>
            <%= checkbox_array.count(checkbox_ans) %><br> 
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to surveys_path, class: 'col-lg-2 col-lg-offset-4 btn btn-info' do %>
  <i class="glyphicon glyphicon-ok-circle"></i> Finish
<% end %>

app/views/given_answers/new.html.erb
<h1>New given_answer</h1>

<%= render 'form' %>

<%= link_to 'Back', given_answers_path %>

app/views/given_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Survey:</strong>
  <%= @given_answer.survey_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @given_answer.question_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @given_answer.answer %>
</p>

<%= link_to 'Edit', edit_given_answer_path(@given_answer) %> |
<%= link_to 'Back', given_answers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
 <%= javascript_include_tag "jquery-1.4.2.min", "rails", "highcharts" %>
 <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="css/bootstrap.css">
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  <!--Link to include glyphicon in rails -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <!--Link to include iconic font awsome in rails-->
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  <script src="path/to/sweet-alert.min.js"></script>
  <link rel="stylesheet" href="path/to/sweet-alert.css" />
</head>

<body>
<div class="header">
    <%= render 'shared/nav' %>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
</div>      
<div class="container">

<%= yield %>

</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', survey_question_path(question.survey,question) %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Products</h1>

<p>
  Download:
  <%= link_to "PDF", questions_path(format: "pdf") %> |
  <%= link_to "XLS", questions_path(format: "xls") %>
</p>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/surveys/_form.html.erb
<%= form_for(@survey,) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_question.html.erb
 <% if @questions.empty? %>

      <div class = "alert alert-danger">
         <center><h3> Questions not available.</h3></center>
      </div>
        <%= link_to surveys_path, class: 'col-lg-1 col-lg-offset-5 btn btn-info' do %>
        <i class="glyphicon glyphicon-ok-circle"></i> Home
        <% end %>
    <% else %>
      <div class="panel-group">
        <div class="panel panel-info">
          <div class="panel panel-heading">
          </div>
          <div class="panel-body">

            <%= form_for [@survey,@given_answer] do |f| %> 
              <%= hidden_field_tag "total_question" , @questions.size %>
              <% @questions.each_with_index do |question,index| %>
                  <%= f.fields_for("#{question.id}",question) do |ans|%>
                  <%= render_answer_form_helper(question,ans,index) %>
                <% end %>
              <% end %>
              <br>
              <center><%= f.submit "Save" , class: "btn btn-success" %></center>
            <% end %>
          </div>
        </div>
    </div>
<% end %>




    

app/views/surveys/edit.html.erb
<h3>Report</h3>

<html>
<head>

  </head>
  <body>
  	<%= pie_chart GivenAnswer.group(:answer).count %>
  
  	<div id="orders_chart" style="height:560px;width:600px;"></div>
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
<tr>
	<th>Question</th>
	<th>Answers</th>
	<th>Total Attempt</th>
	<th>Count</th>
	
</tr>
<% @question_results.map(&:question).uniq.each do |que| %>
	<tr>
		<td>
 			<%= que.question_text %>
 		</td>
 		<% @options = GivenAnswer.where(:question_id => que.id) %>
 		<td> 
 			
 				<% checkbox_array=[] %>				
 				<% @options.map(&:answer).uniq.each do |option| %>

 					<% if que.types == "checkbox" %>
 						<% checkbox_array=checkbox_array + option.split('\n') %>
 					<% else %>
 					<%= option %><br>
 					<% end %> 	
 				<% end %>
 				<% checkbox_array.uniq.each do |checkbox_ans| %>
					<%= checkbox_ans %><br>						
				<% end %>

 		</td>
 		
 	<td>				
 		<%= @options.count %>
 	</td>
 	
 	<td>	
 		<% checkbox_array=[] %>	
 		<%  @options.map(&:answer).uniq.each do |option| %>
 			<% if que.types == "checkbox" %>
 				<% checkbox_array=checkbox_array + option.split('\n') %>					
			<% else %>			
 				<% @counts = GivenAnswer.where(:answer => option) %>	
 				<%= @counts.count %><br>		
 			<% end%>
 		<% end%>
 				<% checkbox_array.uniq.each do |checkbox_ans| %>
 					<%= checkbox_array.count(checkbox_ans) %><br>	
				<% end %>

 	</td> 	
 </tr>
<% end %>
</table>

<%= link_to surveys_path, class: 'col-lg-2 col-lg-offset-4 btn btn-info' do %>
  <i class="glyphicon glyphicon-ok-circle"></i> Home
<% end %>
</body>
</html>

app/views/surveys/index.html.erb
<h3>Select survey</h3>
<html>
<head>
  </head>
<body>
<div class="table-responsive">
<table class="table table-hover">
  <thead align="center">
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>

        <td>
          <%= link_to survey.name, survey , class: "btn btn-link" %></td>
        <td><%= link_to survey , class: "btn btn-warning btn-md" do %>
            <i class="glyphicon glyphicon-play"></i>Take Survey 
            <% end %>
          </td>

        <td>
          <% if user_signed_in? %>
            <% if current_user.id == User.first.id %>
              <%= link_to edit_survey_path(survey),class: "btn btn-info btn-md" do %>
                  <i class="glyphicon glyphicon-open"></i>Report
              <% end %>
            </td>
            <% end %>
          <% end %>
        <td><%#= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Survey', new_survey_path , class: "btn btn-primary" %>



<% if user_signed_in? %>

  <% if current_user.id == User.first.id %>

<%= link_to new_survey_path , class: "btn btn-success btn-md" do %>
    <i class="glyphicon glyphicon-plus"></i>Create Survey
<% end %>
<% end %>
<% end %>
</body>
</html>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h3><%= @survey.name %></strong></h3>
</p>

<%= render 'question' , locals: @survey %>